### ISSUE TITLE
Warning for new release which-key mapping 

### ISSUE THREAD

**Issue by viratalbu1** [LunarVim/Launch.nvim#193]
There is warning for related to which-key plugin , Since which-key is updated to new release which-key Register are depreciated now we would require new mapping for which key mapped with latest release.

Here is the screen shot

![image](https://github.com/user-attachments/assets/b22f7dd8-eb69-439a-ab25-db5a1a35f473)

![image](https://github.com/user-attachments/assets/759e82de-7560-4c76-8a53-88d384692533)

![image](https://github.com/user-attachments/assets/dad0769b-c768-403e-838f-dce730aba6ef)

**Comment by wjmadden** [comment]
Take a look at [Pull request 188](https://github.com/LunarVim/Launch.nvim/pull/188) and see if that fixes your issue.

**Comment by MickTheRus** [comment]
The Pull request has been merged after.... some time.
